plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.compileJava {
    options.encoding "UTF-8"
}

sourceSets {
    main {
        java {
            srcDirs("src/main/java")
            exclude("**/*.kt")
        }
        resources {
            srcDirs("src/main/resources")
            exclude("**/*.java", "**/*.kt")
        }
    }
    test {
        java {
            srcDirs("src/test/java")
            exclude("**/*.kt")
        }
        resources {
            srcDirs("src/test/resources")
            exclude("**/*.java", "**/*.kt")
        }
    }
}

dependencies {
    annotationProcessor libs.lombok
    compileOnly libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    implementation libs.slf4j
    testImplementation libs.logback

    // testImplementation libs.junit_bom
    // testImplementation libs.junit_jupiter
    // testRuntimeOnly libs.junit_platform
}

/*
test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
 */
